version: '2'
services:
    sopoc-app:
        image: sopoc
        external_links:
            - sopoc-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sopoc?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    sopoc-mysql:
        extends:
            file: mysql.yml
            service: sopoc-mysql
